### ISSUE TITLE
Issue with SLiM installation 

### ISSUE THREAD

**Issue by annaiesenfeld** [MesserLab/SLiM-Extras#12]
As sudo, having installed the all dependencies (cmake, qmake, qt5-default, curl) , downloaded the installation script DebianUbuntuInstall.sh (made it executable) and then executed sudo ./DebianUbuntuInstall.sh - I got this output:

"CMAKE_BUILD_TYPE is Release
BUILD_SLIMGUI is ON
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so
-- Configuring done
CMake Error at CMakeLists.txt:160 (add_executable):
Target "SLiMgui" links to target "OpenGL::GL" but the target was not found.
Perhaps a find_package() call is missing for an IMPORTED target, or an
ALIAS target is missing?

-- Generating done
-- Build files have been written to: /tmp/BUILD
Build failed. Please see the output and make a post on the slim-discuss mailing list.
The output from this build is stored in '/var/log/' as SLiM-CMakeOutput-2021-04-26T17:34:56+01:00.log.
You may be asked to upload this file during a support request.%
"

My guess is that something is wrong with OpenGL, but I am not sure where to go from there. 

[SLiM-CMakeOutput-2021-04-26T173456+0100.log](https://github.com/MesserLab/SLiM-Extras/files/6379070/SLiM-CMakeOutput-2021-04-26T17.34.56%2B01.00.log)

**Comment by bryce-carson** [comment]
Thank you, @annaiesenfeld, for asking for support. I'm reading through your log and looking into the CMake error.
Can you also post the output of `uname -a`?

**Comment by annaiesenfeld** [comment]
Thank you for looking into it!

As for the uname -a output, I think this is it: 

Linux Clifford 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux

**Comment by bryce-carson** [comment]
@annaiesenfeld, I am working on an actual package for Debian & Ubuntu systems; if you're mostly after SLiMgui, which I assume is the case, then this should be faster (the binaries are pre-built) and easier. Would you be willing to test the package? It should be feature-complete, but if you encounter any errors they would be helpful for development purposes.

[![deb](https://user-images.githubusercontent.com/51974245/116131131-3da6bd00-a689-11eb-9108-c7cba7ae8e42.png)](https://github.com/MesserLab/SLiM-Extras/files/6379226/slim-sim_3.6-1_amd64.zip)

**Comment by bryce-carson** [comment]
For the script, it might be that you're the first Debian user and an extra library is required.
Can you run these commands, @annaiesenfeld?

`dpkg-query -s libqt5opengl5-dev`. If the package is not intalled, or does not read "installed ok", can you install the package and try the script again?

Please note, if you're willing to and are using the Debian package above don't use the script any longer because it will overwrite the binaries that the package is installing. If the Debian package works for you, then you're completely done! :)

**Comment by annaiesenfeld** [comment]
Thank you for your previous suggestions.

I ran sudo dpkg -i slim-sim_3.6-1_amd64.deb  and got the following: 

dpkg: dependency problems prevent configuration of slim-sim:

slim-sim depends on libc6 (>= 2.29); however:
Version of libc6:amd64 on system is 2.24-11+deb9u4. 

slim-sim depends on libgcc-s1 (>= 3.0); however:
Package libgcc-s1 is not installed. 

slim-sim depends on libqt5core5a (>= 5.14.1); however:
Version of libqt5core5a:amd64 on system is 5.7.1+dfsg-3+deb9u3. 

slim-sim depends on libqt5gui5 (>= 5.14.1) | libqt5gui5-gles (>= 5.14.1); however:
Version of libqt5gui5:amd64 on system is 5.7.1+dfsg-3+deb9u3.

Package libqt5gui5-gles is not installed.

slim-sim depends on libqt5widgets5 (>= 5.14.1); however:
Version of libqt5widgets5:amd64 on system is 5.7.1+dfsg-3+deb9u3.

slim-sim depends on libstdc++6 (>= 9); however:
Version of libstdc++6:amd64 on system is 6.3.0-18+deb9u1.


And when I tried to install the package (sudo apt-get install package-name) I got the following errors respectively:

libc6 is already the newest version (2.24-11+deb9u4).

Package libgcc-s1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

libqt5core5a is already the newest version (5.7.1+dfsg-3+deb9u3).
libqt5core5a set to manually installed.

libqt5gui5 is already the newest version (5.7.1+dfsg-3+deb9u3).
libqt5gui5 set to manually installed.

Package libqt5gui5-gles is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

libqt5widgets5 is already the newest version (5.7.1+dfsg-3+deb9u3).
libqt5widgets5 set to manually installed.

**Comment by bryce-carson** [comment]
Thank you. I'm looking into this further and will be testing on a Debian 10 machine.

**Comment by bryce-carson** [comment]
Okay, @annaiesenfeld . On a freshly installed Debian 10 (Buster) machine, with `gcc g++ cmake qt5-qmake qt5-default` installed, I am able to build and install SLiMgui and the command-line programs with the script.

Based on the complaints of dpkg, I'm going to assume you're using Debian 9 or 8. I _will not_ expect you to upgrade your system unless Qt 5.9.5 is unavailable, which is the earliest version of Qt5 that is supported by SLiMgui.

Can you ensure that you have `gcc` and `g++` installed? Those two packages were not earmarked and installed as dependencies or as recommended packages when I installed the three packages that the script depends on (`qt5-default qt5-qmake cmake`).

Further, I'm not totally familiar with `dpgk`'s workings, and I would recommend using `apt` unless you're aware of some reason not to. I'm not sure if `dpkg` handles dependencies the same way `apt` does. The only time I've ever used `dpkg` is in the installation script for SLiMgui to check if packages are installed.

Let me know if `apt install gcc g++; ./DebianUbuntuInstall.sh` works.

**Comment by annaiesenfeld** [comment]
I've installed the  .deb file, for which I used dpkg since I thought apt was only for installing from a repository. I did a search and also tried:

sudo apt install ./slim-sim_3.6-1_amd64.deb

But got the following similar message as dpkg

Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'slim-sim' instead of './slim-sim_3.6-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.

The following information may help to resolve the situation:

The following packages have unmet dependencies:
slim-sim : Depends: libc6 (>= 2.29) but 2.24-11+deb9u4 is to be installed
Depends: libgcc-s1 (>= 3.0) but it is not installable
Depends: libqt5core5a (>= 5.14.1) but 5.7.1+dfsg-3+deb9u3 is to be installed
Depends: libqt5gui5 (>= 5.14.1) but 5.7.1+dfsg-3+deb9u3 is to be installed or
libqt5gui5-gles (>= 5.14.1) but it is not installable
Depends: libqt5widgets5 (>= 5.14.1) but 5.7.1+dfsg-3+deb9u3 is to be installed
Depends: libstdc++6 (>= 9) but 6.3.0-18+deb9u1 is to be installed
E: Unable to correct problems, you have held broken packages.


Re gcc and g++  have already been installed and the version is 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) — maybe this needs to be updated (but updating to the latest gcc conflicts with my Matlab installation, which always needs an older version).

So I am guessing that apt install gcc g++; ./DebianUbuntuInstall.sh won't work, since gcc and g++ are already installed, and this was the original error.

**Comment by bryce-carson** [comment]
Okay. I should have expected it, really, but the package I sent you depends on newer libraries than are available on your Debian 9 (Stretch) system. I built that package in Ubuntu 20.10; it's not built against any other version of libraries, so it's expecting the versions that my system had. Not ideal, very much still experimental - it was worth a shot, I thought, but building the software against the libraries you have available and installed is best, of course.

From the _Qt5 dependencies_ page of the Qt Wiki, it states:
>By default, Qt also expects XCB and OpenGL drivers to be installed. Usually, many modern distros already do have those packages included by default. If you don't have other OpenGL drivers (supplied by graphics vendor, for example), you can use the mesa package: `sudo apt-get install libx11-xcb-dev libglu1-mesa-dev`

Please try that, and if the build and installation script still fails post the output again and I'll see if I can find any good information on the internet.

As the DebianUbuntuInstall.sh script will build against the libraries you _currently have installed_, that would certainly be compatible with your setup and configuration. Since you can't update some libraries and binaries, using the libraries you have installed will work; if I rebuilt the package against Debian 9 for you, there would still be a good chance that it would require a newer library than what you have installed.

If you're unable to install the dependencies in the above quotation, you might try a chroot. That would give you a separate environment in which to run the build and installation script after installing the necessary dependencies inside it. How you would use the built software alongside your other graphical applications, access files outside it, and other peculiarities aren't within my knowledge base, unfortunately. The chroot only applies to the processes started inside the chroot, so applications outside it would be unaffected and use the libraries and binaries in your regular `/`. I don't have any instructions for that, however.

**Comment by annaiesenfeld** [comment]
I did sudo apt-get install libx11-xcb-dev libglu1-mesa-dev and those packages were already installed and updated to their newest versions. Just in case something had changed in the intervening period, I tried sudo ./DebianUbuntuInstall.sh again, but I get the same error message.

Is there a way of  installing the latest version of slim without the gui? I think the gui/opengl/qt5 may be the issue, not the core software instead.

**Comment by bryce-carson** [comment]
Interesting.

Yes, absolutely. I'll make a note to improve the documentation so it's more clear.

The script and packages make it easier to install the gui. If you only want the command line programs, follow the instructions in the manual section _Building from Source_.

**Comment by bryce-carson** [comment]
Hi @annaiesenfeld, were you able to build the command-line programs (`slim` and `eidos`) on your Debian 9 machine successfully?

**Comment by annaiesenfeld** [comment]
Hi, yes.
Sorry, I completely forgot to follow up. 
Thank you for your help!

**Comment by bhaller** [comment]
Hi @bryce-carson – I didn't follow all of the above discussion, but is there a problem above that still needs to be resolved?  It's great that she got `slim` and `eidos` installed, but why was she unable to install SLiMgui?

**Comment by bryce-carson** [comment]
@bhaller There was an issue with OpenGL on their machine. I still not sure what the exact reason was, but it might have to do with their installation of Matlab, which was holder other packages at an earlier version.

**Comment by bhaller** [comment]
I see, thanks.
