### ISSUE TITLE
Improve Ubuntu installer

### ISSUE THREAD

**Issue by eoli3n** [MesserLab/SLiM-Extras#21]
@bryce-carson 

The ubuntu install script is dirty, it puts unmanaged files in hardcoded directories.
Then no way to track files, no way to properly upgrade SLiM, no way to install in a custom dir.

- Please add the ability to change the PREFIX dir for building SLiM
- Create a PPA : https://help.launchpad.net/Packaging/PPA to provide a clean deb package repository.

**Comment by bryce-carson** [comment]
I had created a DEB nearly a year ago but got stuck on launchpad and didn't finish.

I'll do it today if you can test the package and let me know if there's any problems with the description of the package.

DEB is confusing after having such a pleasant time with RPM.

**Comment by eoli3n** [comment]
I'll test anything you need ;) Let me know when this is ok.

**Comment by bhaller** [comment]
Hi @bryce-carson.  I'm here in the peanut gallery.  Is the plan to provide the current install option, plus also this new option?  Or to switch over?  Anyhow, whatever you think is best; as you know, my understanding of these Linux install issues is minimal at best.  :->  But I hope the current install path can continue to work at least until the next SLiM release; and then in that next SLiM release the install instructions in the manual, etc., can get modified as needed.  Thanks!

**Comment by bryce-carson** [comment]
> Hi @bryce-carson.  I'm here in the peanut gallery.  Is the plan to provide the current install option, plus also this new option?  Or to switch over?  Anyhow, whatever you think is best; as you know, my understanding of these Linux install issues is minimal at best.  :->  But I hope the current install path can continue to work at least until the next SLiM release; and then in that next SLiM release the install instructions in the manual, etc., can get modified as needed.  Thanks!

It will be a clean break from the install script currently provided to providing only the Debian package.

Once it's ready we should update the install section of the manual at the same time, rather than wait till next release. It would save anyone installing SLiM on Debian now from any unforeseen edge cases if/when they upgrade to the next release.

**Comment by bhaller** [comment]
Hmm.  Updating the manual in mid-stream without doing a new release is not something I've done before, for more than trivial edits, and I don't think it's a good idea; it has the potential to confuse people.  People might have downloaded the manual for 3.7 already, and are now using it as a resource to tell them how to install SLiM on this or that machine as they work.  If the ground shifts under them, their installs will just stop working (if I understand what you propose correctly), and they will not know to download a new copy of the manual.  Posting on slim-discuss about it is not a great solution, since many SLiM users (unfortunately) do not subscribe to slim-discuss.  I feel pretty strongly that things like this should only change when a new release comes out; people expect stuff to change at that point.  So... if you want this to be a clean break, then let's postpone rolling out this change until the next release.  Is that OK?  (I don't know when the next release will be.)

**Comment by eoli3n** [comment]
Or make a special 'empty' release for this.

**Comment by bhaller** [comment]
Doing a release is quite a large amount of work, so I'm not inclined to do one just for this reason; the current install solution may not be ideal, but it has been working fine for people overall, as far as I can tell.

**Comment by eoli3n** [comment]
This reason is a huge one. I need to install SLiM on 800 hosts, as is I can't.

> I feel pretty strongly that things like this should only change when a new release comes out; people expect stuff to change at that point.

You said that you want to use a release as notifier for a new installer.

An installer is a way to provide code, you can change the installer without any new release. Just update the readme, and let new users (who installs the tool) use it. Existing users, will be impacted automatically on the next release when trying to upgrade.

**Comment by bryce-carson** [comment]
We can provide the Debian package alongside the installation script until the next release. We can mention it in in the Google group, but we don't need to worry about the current Debian and Ubuntu userbase becoming confused if we only provide it as a (better) alternative on the GitHub. When people are consulting the manual only (and aren't looking at the GitHub) for installation  instructions they will likely use the script still (assuming they're following the path of: MesserLab website to manual, manual to installation instructions).

Even though the current script is not ideal it was written with XDG specifications at hand so it is robust (apart from any edge cases that `dpkg` might throw out). The package will just provide niceties for automatic upgrades and easier software removal (gasp!).

When the next release does occur, and we update the installation instructions in the manual, we can remove the link to the installation script from the table on [MesserLab/SLiM](https://github.com/MesserLab/SLiM#installation).

**Comment by bhaller** [comment]
OK, that sounds good @bryce-carson.  I just want the existing install instructions that are in the manual to continue to work seamlessly until the next release, otherwise I guarantee we will get complaints and confusion.  :->  Thanks.

**Comment by bryce-carson** [comment]
> This reason is a huge one. I need to install SLiM on 800 hosts, as is, I can't.

That's quite the number of desktop workstation installs. If you're only looking for the command-line, however, the script follows exactly the same build instructions that a Debian user would normally follow (excepting the included desktop integration).

The Debian package shouldn't take too long, I still have my old control file. It just needs to be updated and verified, then the source package uploaded to a PPA on launchpad.

**Comment by eoli3n** [comment]
> If you're only looking for the command-line, however, the script follows exactly the same build instructions that a Debian user would normally follow (excepting the included desktop integration).

Yep, but we provide only to ways to install:
- compiling from source with PREFIX on a custom path, mounted with NFS 
  Maybe SLiM have build instructions, but the README points to the ubuntu installer script which curl a zip file, etc... I'm a user, I follow instructions, I don't have much time for reverse engineering, and to adapt install instructions for each tool I install, I manage more than 400 applications.
- install a managed package: which is the right way, to be able to udpate properly

**Comment by bryce-carson** [comment]
> > If you're only looking for the command-line, however, the script follows exactly the same build instructions that a Debian user would normally follow (excepting the included desktop integration).
> 
> Yep, but we provide only to ways to install:
> 
>     * compiling from source with PREFIX on a custom path, mounted with NFS
>       Maybe SLiM have build instructions, but the README points to the ubuntu installer script which curl a zip file, etc... I'm a user, I follow instructions, I don't have much time for reverse engineering, and to adapt install instructions for each tool I install, I manage more than 400 applications.
> 
>     * install a managed package: which is the right way, to be able to udpate properly, thanks for working on this BTW :)

The audience of the SLiM manual is end-users (biologists and students). It includes instructions for building and installing SLiM.

The build instructions are standard:
1. `git clone --depth 1 --branch v3.7 https://github.com/MesserLab/SLiM.git`
2. `mkdir buildSLiM && cd buildSLiM`
3. `cmake ../SLiM`
4. `make slim`
5. `make install slim`

Since it is a standard make file you can specify an install prefix with whatever option is normal (see `man make`).

If you are needing the SLiMgui for that number of workstations then it would be best to wait for the Debian package. Desktop integration is tricky, but that is what the installation script was written for.

**Comment by eoli3n** [comment]
I will deploy Slim in a French University, that's why that huge host number.
I'll wait, thanks !

**Comment by bryce-carson** [comment]
Glad to hear that there is a university with that many workstations running Linux. It is not very common.

**Comment by bryce-carson** [comment]
@eoli3n, I now have a successful build for Ubuntu Focal Fossa on Launchpad. I will be copying the package and rebuilding for the other newest Ubuntu releases, but it isn't working for now.

I am still working trying to understand if Debian packages can be built in Launchpad. As I understand it, non-native Debian packages on Launchpad.net are just Ubuntu packages without any `ubuntu[[:digit:]]` or `ppa[[:digit:]]` suffixing in the package name.

Debian & Ubuntu packaging is _painful_, 📦😭 which is why my first effort was never released (even though it was a success).

Feel free to test if the Focal Fossa build works on your Debian machines. The package names that Ubuntu uses for all of the `Build-Depends` of SLiM are the same as those package names in Debian, so nothing should be missing. The greatest concern is whether the version of `debhelper` on the release of Debian that you are using supports compatability-level nine (`echo "9" > debian/compat`). If it doesn't support that, neither does the package for SLiM.

1. `sudo add-apt-repository ppa:bryce-a-carson/slim-sim`
2. `sudo apt-get update`
3. `sudo apt install slimsim`; beware that the package name does _not_ contain a hyphen like the PPA does.

⚠️ Do note that the package for _SLiM: Selection on Linked Mutations_ conflicts with the package for the (effectively) defunct Simple Login Manager (also uses the SLiM abbreviation; see ["SLiM" in the Arch Wiki](https://wiki.archlinux.org/title/SLiM)). I have not bothered to include a `Conflicts` field in the package. I'll get around to sanitizing the package this summer (May through August and no sooner) and hopefully making it more aligned with the Debian Policy Manual, but no promises.

@bhaller For now I am not comfortable directing *anyone* to the Debian package until some testing has been done. We could make an announcement on #slim-discuss that we would *like* people to test the package, or we might just leave it here in the GitHub Issue pile for people to happen upon if they're having issues with the installation script.

For me to feel comfortable publicly releasing the package, I want to better understand the Debian packaging system. It is difficult. As I told Kirszling (eoli3n) above, Debian packaging is painful. The documentation is pretty abstruse and difficult to navigate. Canonical doesn't have have any packaging documentation of their own worth a dollar either, so it's all Debian documentation and third-party websites. This was not fun now, nor when I first did it a year ago. 😆 😭

Let me know what you think about testing, announcing, and releasing. @eoli3n will be the first beta tester.

**Comment by eoli3n** [comment]
> Feel free to test if the Focal Fossa build works on your Debian machines

My nodes run Ubuntu Focal.

```bash
$ LANG=C apt install slimsim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 slimsim : Depends: libqt5core5a (>= 5.14.1) but 5.12.8+dfsg-0ubuntu2.1 is to be installed
           Depends: libqt5gui5 (>= 5.14.1) but 5.12.8+dfsg-0ubuntu2.1 is to be installed or
                    libqt5gui5-gles (>= 5.14.1) but it is not going to be installed
           Depends: libqt5widgets5 (>= 5.14.1) but 5.12.8+dfsg-0ubuntu2.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by bryce-carson** [comment]
I see what's happening. I'll correct that and push a new package release this week. Probably Thursday.

**Comment by bryce-carson** [comment]
@eoli3n, the new package release has been uploaded and built successfully. I'm waiting for publishing to the repository now. Test it out, please, and let me know if it works for you now. Don't forget to use VNC or something and check that the desktop integration is correct in the desktop environment the workstations are using.

**Comment by eoli3n** [comment]
It's working perfectly ! Except for the mime icon, it seems to fallback or the general txt icon.

- [x] Desktop / application icon displays correctly.
- [x] Symbolic application icon appears correctly when using a high-contrast theme.
- [x] SLiM appears in Education or Science section of an application menu if a sectioned application menu is used by the desktop environment (like in Gnome 2 or MATE).
- [ ] ``.slim`` MimeType icon appears correctly.

![slim_edit](https://user-images.githubusercontent.com/14223657/153369789-6fc4c1d4-d02c-43ef-9415-e6c329f113d6.png)

**Comment by bryce-carson** [comment]
Does the MimeType icon show correctly if you manually run `update-mime-database`?

The icon and the XML are installed to the correct locations, and dpkg should have run a hook for updating the MIME cache, but perhaps something didn't work correctly with your desktop environment.

What desktop environment are the nodes running?

**Comment by bryce-carson** [comment]
Please also check `dpkg -S /usr/share/mime` and `dpkg -S /usr/share/icons` to be sure, @eoli3n .

**Comment by eoli3n** [comment]
The DE is XFCE
```bash
$ update-mime-database /usr/share/mime

$ dpkg -S /usr/share/mime
wxmaxima, codeblocks-common, meshlab, massif-visualizer, chemical-mime-data, seaview, auto-multiple-choice-common, libreoffice-common, mysql-workbench-community, meld, omnotebook, algobox, ugene, synthv1-common, software-properties-gtk, libkf5coreaddons-data, scribus-data, qtcreator-data, emboss, docutils-common, lmms-common, audacity-data, grace, monodevelop, qgis, shared-mime-info, remmina, gcr, slimsim: /usr/share/mime

$ dpkg -S /usr/share/icons
elementary-xfce-icon-theme, gimp-data, devhelp-common, ristretto, xfce4-session, xfce4-statusnotifier-plugin, xfce4-notes, xfce4-netload-plugin, xfce4-panel, xfce4-indicator-plugin, xfce4-dict, xfce4-screenshooter, xfce4-cpugraph-plugin, xfce4-mailwatch-plugin, thunar-volman, mugshot, indicator-session, codeblocks-common, r-base-core, grass-core, xfce4-power-manager-data, indicator-messages, blueman, thunderbird, onboard, apport, gnome-control-center-data, meshlab, massif-visualizer, calf-plugins, nautilus-data, firefox, fastqc, chemical-mime-data, umbrello, modemmanager, qemu-system-data, spyder, synthv1, seaview, qjackctl, vlc-data, xcas, xemacs21-support, unity-settings-daemon, gnome-packagekit-data, ncbi-data, veyon, auto-multiple-choice-common, openjdk-11-jre:amd64, update-notifier, sagemath-jupyter, libreoffice-common, mysql-workbench-community, soundconverter, pyzo, singular-data, qsynth, mpv, famfamfam-silk, meld, xfig, ugene, synthv1-common, gnome-icon-theme, octave-common, software-properties-gtk, krita-data, kazam, scribus-data, qtcreator-data, inkscape, imagemagick-6.q16, openjdk-8-jre:amd64, gtkterm, groovy, gprolog, glade, filezilla-common, lmms-common, xfwm4, xfce4-pulseaudio-plugin:amd64, menulibre, thunar-data, audacity-data, xfce4-notifyd, imagej, hydrogen-data, grace, emacs-common, dia-common, xterm, xfdesktop4-data, xfce4-whiskermenu-plugin, xfce4-weather-plugin, xfce4-taskmanager, xfce4-settings, sgt-puzzles, lightdm-gtk-greeter-settings, lightdm-gtk-greeter, libexo-common, catfish, atril-common, monodevelop, wine, thunar-archive-plugin, sgt-launcher, libxfce4ui-utils, x2goclient, qgis, yelp, yaru-theme-icon, xcursor-themes, usb-creator-gtk, ubuntu-mono, transmission-common, totem-common, simple-scan, shotwell-common, seahorse, rygel, rhythmbox-data, remmina-common, orca, libpeas-common, libgeocode-glib0:amd64, ibus-data, humanity-icon-theme, hicolor-icon-theme, gnome-todo-common, gnome-terminal, gnome-system-monitor, gnome-sudoku, gnome-startup-applications, gnome-shell-common, gnome-screenshot, gnome-power-manager, gnome-online-accounts, gnome-mines, gnome-mahjongg, gnome-logs, gnome-font-viewer, gnome-disk-utility, gnome-characters, gnome-calendar, gnome-calculator, gnome-bluetooth, gnome-accessibility-themes, gedit-common, gcr, fwupd, file-roller, eog, evince, dmz-cursor-theme, deja-dup, cheese-common, baobab, aptdaemon-data, aisleriot, adwaita-icon-theme, slimsim, vim-common, engrampa-common: /usr/share/icons
```
But still no icon

**Comment by bryce-carson** [comment]
Is the mimetype at least recognized, such that if no other software is already configured to open `.slim` files (such as the Ruby .slim framework files), then .slim files are associated with SLiMgui and the filename is shown as "text/slim" when you're inspecting file properties?

**Comment by bryce-carson** [comment]
That's interesting, given the mimetype was installed.

What's the output of this command?

`mimetype --language en --debug untitled.slim`

**Comment by bryce-carson** [comment]
@eoli3n
I did a test in a virtual machine with Focal Fossa (without XFCE) and discovered that if a file is empty, the desktop environment will always report it as a text/plain file regardless of the file extension and use the respective text-plain icon from the current icon theme.

If you open SLiMgui from the menu, not by opening the (presumably) empty file you created (`toto.slim`) from the desktop, and save the default model somewhere with a `.slim` extension you will see that the same information is reported by `mimetype --debug [file]` for both files, but the desktop environment will make different choices for which icon to display and what mimetype to report for the empty file and the non-empty file.

This holds for other filename extensions: `.py`, `.sh`, `.doc`, `.png`, etc.

- [ ] `.slim` MimeType icon appears correctly.

I wonder why desktop environments do that. I couldn't find anything about it in the _Shared MIME-info Database_ specification.

**Comment by eoli3n** [comment]
Good to know. To me, everything's ok, can I then use that ppa in production ?

**Comment by bryce-carson** [comment]
> Good to know. To me, everything's ok, can I then use that ppa in production ?

Yep! Good to go!

You might want to run the check commands for `slim -ts` and `eidos -te`, but there shouldn't have been any build issues that would cause the binaries to diverge from expected operation.

@bhaller this issue can now be closed. :)

**Comment by eoli3n** [comment]
```bash
root@focal-uefi:~# slim -testSLiM

SUCCESS count: 99285
root@focal-uefi:~# slim -testEidos

SUCCESS count: 6475
```
Thanks @bryce-carson !

**Comment by bryce-carson** [comment]
You're welcome! I hope the students enjoy learning with SLiM.
