### ISSUE TITLE
Failed desktop integration

### ISSUE THREAD

**Issue by mtomasini** [MesserLab/SLiM-Extras#26]
Hey all,
I'm trying to install the Ubuntu version of SLiMgui using the `DebianUbuntuInstall.sh` script as described at page 61-62 of the SLiM Manual. The installation to `/usr/bin` is successful, however the desktop integration fails, due to some missing files:

```bash
Installation to /usr/bin was successful. Proceeding with desktop integration.
mv: cannot stat '../SLiM/org.messerlab.slimgui-mime.xml': No such file or directory
mv: cannot stat '../SLiM/org.messerlab.slimgui.desktop': No such file or directory
mv: cannot stat '../SLiM/org.messerlab.slimgui.appdata.xml': No such file or directory
xdg-mime: file '/usr/share/mime/packages/org.messerlab.slimgui-mime.xml' does not exist
Desktop integration failed. 
```

I tried removing the three lines from the script, but of course that's a naif solution that doesn't work since I assume they are needed in order to run `update-mime-database`. If it helps, I'm running Ubuntu 22.04, let me know if you need other information.

Any help would be great, but is not urgent - since I can open the gui through the command line. Thanks!

**Comment by bhaller** [comment]
Hi @bryce-carson.  This issue came up in the Stockholm workshop, I think, and now it has come up for someone in the Ancona workshop also.  I think you had a planned change to the script, involving checking the CMake version or something, no?  We discussed it at the time.  If that fix is not ready, can you please explain a workaround here, so that users who hit this can still get things installed?  Thanks!

**Comment by bryce-carson** [comment]
> Hey all, I'm trying to install the Ubuntu version of SLiMgui using the `DebianUbuntuInstall.sh` script as described at page 61-62 of the SLiM Manual. The installation to `/usr/bin` is successful, however the desktop integration fails, due to some missing files:
> 
> ```shell
> Installation to /usr/bin was successful. Proceeding with desktop integration.
> mv: cannot stat '../SLiM/org.messerlab.slimgui-mime.xml': No such file or directory
> mv: cannot stat '../SLiM/org.messerlab.slimgui.desktop': No such file or directory
> mv: cannot stat '../SLiM/org.messerlab.slimgui.appdata.xml': No such file or directory
> xdg-mime: file '/usr/share/mime/packages/org.messerlab.slimgui-mime.xml' does not exist
> Desktop integration failed. 
> ```
> 
> I tried removing the three lines from the script, but of course that's a naif solution that doesn't work since I assume they are needed in order to run `update-mime-database`. If it helps, I'm running Ubuntu 22.04, let me know if you need other information.
> 
> Any help would be great, but is not urgent - since I can open the gui through the command line. Thanks!

Hi, I'm sorry I didn't reply. I never saw this issue; it doesn't appear that any mention of it occurred elsewhere, however I do know that I was dealing with _this issue_ previously in https://github.com/MesserLab/SLiM/issues/441.

I don't have a work-around right now, because that requires dealing with some fiddly temporary directory creation and deletion; the deletion of the temporary directory should have been the responsibility of the operating system---that's the purpose of `/tmp`, after all---so that's why a work-around for the current script is not tenable.

An improved version of the script is incoming. I hope to finish it today. I'll include an option like `--work-around` or something that will _only_ perform desktop integration so that people who have encountered this issue will have a fix without needing to rebuild and reinstall SLiM and SLiMgui.

**Comment by bryce-carson** [comment]
> Hi @bryce-carson. This issue came up in the Stockholm workshop, I think, and now it has come up for someone in the Ancona workshop also. I think you had a planned change to the script, involving checking the CMake version or something, no? We discussed it at the time. If that fix is not ready, can you please explain a workaround here, so that users who hit this can still get things installed? Thanks!

Sorry about that, the re-work of the script fell by my side when I got busy with my new summeR job, which started on May 1st. I'll get up and running on this today so that people aren't confused and inconvenienced.

**Comment by bhaller** [comment]
Hi @bryce-carson.  Yes, I was thinking of #441; I was a bit puzzled as to where all the discussion had vanished to!  The plan sounds fine, although I wouldn't worry about the `--work-around` option really; it's only one person who is presently hitting this, so better to just keep the fix simple, I'd say – not a big deal for that one person to have to re-run the install.  Anyhow, thanks!  I hope the summer job is good!
